name: Task Manager API CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0'

    - name: Restore dependencies
      run: dotnet restore TaskManagerAPI/TaskManagerAPI.csproj

    - name: Build project
      run: dotnet build TaskManagerAPI/TaskManagerAPI.csproj --no-restore

    - name: Publish project
      run: dotnet publish TaskManagerAPI/TaskManagerAPI.csproj -c Release -o output

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: taskmanager-api-build
        path: output
